name: Run a Workflow Job Directly in the Runner

on:
  workflow_dispatch:
  
jobs:
  runner-job:
    runs-on: ubuntu-latest
    # Service containers running in the `runner-job`
    services:
      # service container name
      redis:
        image: redis
        # health checks to wait until redis is ready
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Mapping port 6379 on service container to the host (runner machine)
          # to enable the job to access the Redis service container
          - 6379:6379
          
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Connect to Redis
        # Runs JavaScript to create a Redis client, populate data and read data
        run: node redisclient.js
        # Environment variable are passed to JavaScript to create Redis client
        env:
          # now need to access Redis service container via localhost as port is mapped to runner machine
          # and the job and Redis service container communication is no longer container to container
          REDIS_HOST: localhost
          # The default Redis port is passed to create the Redis client
          REDIS_PORT: 6379
